site_name: Combination Shape Keys
repo_url: https://github.com/jamesvsnowden/bl_pose_driven_shape_keys
edit_uri: edit/main/docs/
site_description: Combination shape keys for Blender
site_author: James Snowden
nav:
  - About: 'index.md'
  - Installation: 'installation.md'
  - 'User Guide': 'user-guide.md'
  - Issues: 'https://github.com/jamesvsnowden/bl_pose_driven_shape_keys/issues'
theme:
  name: readthedocs
  locale: en
